var newiframe = document.createElement("iframe");
newiframe.setAttribute("src", chrome.runtime.getURL("html/panel.html"));
newiframe.style.width = "100%";
newiframe.style.top = "0";
newiframe.style.left = "0";
newiframe.style.right= "0";
newiframe.style.position = "absolute";
newiframe.style.zIndex = "500";
newiframe.style.height = "80px";
newiframe.style.backgroundColor = "#131313";
document.body.appendChild(newiframe);